### PR TITLE
Feature: Ability to configure a DB connection for translations

### PR DESCRIPTION
**Pull request by cunio-martin**
with this PR, it is possible to configure a separate data source for managing the translations. That way you can have a team working on translations via UI (e.g. Nova) and share the translations across different instances (e.g. development & staging).

- add translation.database.connection key (default is empty)
- updated models and migrations to take connection key into account

### CODE REVIEW

**Comment by joedixon** [comment]
Firstly, thanks for the PR 👍 

Is there any reason you can't do this at the Laravel configuration level? I'm assuming it's because you'd want to switch connections, but only for managing translations and not for the whole app?

Could you provide a little more information about what the workflow would look like?

**Comment by cunio-martin** [comment]
That's exactly the case! We need to separate the connection for translation models from other models. We have the translations managed in a centralized database which is maintained by a group of business users and fed with new keys from new development. Hence all development instances share a common DB for translations.

**Comment by joedixon** [comment]
I think that's a great feature.

I don't typically work with multiple connections so I don't know the answer to this, but should we be defaulting the connection to something like `env('DB_CONNECTION', 'mysql')` or does Laravel use the default if you pass an empty string?

**Comment by cunio-martin** [comment]
It will use the default connection `config('database.default'))`

**Pull request merged**
